# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Noter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'Amplify'
 pod 'AmplifyPlugins/AWSAPIPlugin'
 pod 'AmplifyPlugins/AWSDataStorePlugin'
 pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
 pod 'AWSMobileClient'
 pod 'AWSPinpoint'
 pod 'AWSAPIGateway'

  target 'NoterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoterUITests' do
    # Pods for testing
  end

end
